let player;
let camera;
let canvas;
let canvasHeight;
let canvasWidth;
let world;
let ctx;
let gameSpace = [];
let playerSpeed = 8;
let tempAllObjs = {};
const initialGravity = 0.1;
const gravityIncreaseRate = 0.25;
const maxGravity = 16;
let jumpState = 0;
let gravity = initialGravity;
const cameraLerpInitial = 1;
let cameraLerpFactor = 1;
